import turtle
screen = turtle.Screen()
screen.screensize(500, 500)
screen.bgcolor("cornflowerblue")
t = turtle.Turtle()
t.speed(0)
t.hideturtle()
# grass
t.penup()
t.goto(-400,-400)
t.pendown()
t.pencolor("palegreen")
t.fillcolor("palegreen")
t.begin_fill()
t.setheading(0)
t.goto(400,-400)
t.left(90)
t.forward(300)
t.left(90)
t.forward(800)
t.left(90)
t.forward(300)
t.left(90)
t.forward(800)
t.end_fill()

# flower
t.penup()
t.goto(200,0)
t.pendown()

t.penup()
t.goto(200,0)
t.pendown()
t.pencolor("green")
t.pensize(8)
t.goto(200,-150)
t.pensize(1)


t.penup()
t.goto(200,0)
t.pendown()
t.pencolor("tomato")
t.fillcolor("tomato")
t.begin_fill()
t.circle(25)
t.setheading(90)
t.circle(25)
t.setheading(180)
t.circle(25)
t.setheading(270)
t.circle(25)
t.end_fill()

t.penup()
t.goto(200,-15)
t.pendown()
t.setheading(0)
t.pencolor("yellow")
t.fillcolor("yellow")
t.begin_fill()
t.circle(15)
t.end_fill()

# cloud
t.penup()
t.goto(75,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(70)
t.end_fill()

t.penup()
t.goto(120,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(-20,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(-50,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(170,250)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()
# cloud 2
t.penup()
t.goto(-100,100)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(70)
t.end_fill()

t.penup()
t.goto(-195,65)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(-20,50)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(50)
t.end_fill()

t.penup()
t.goto(-10,120)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(-170,130)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(-100,35)
t.pendown()
t.fillcolor("white")
t.pencolor("white")
t.begin_fill()
t.circle(60)
t.end_fill()

# sun
t.penup()
t.goto(-260,260)
t.pendown()
t.fillcolor("yellow")
t.pencolor("yellow")
t.begin_fill()
t.circle(40)
t.end_fill()

t.pencolor("red")
t.fillcolor("hotpink")
t.penup()
t.goto(-150,-50)
t.pendown()
t.setheading(90)
t.begin_fill()
t.circle(50,180)
t.end_fill()
t.penup()
t.goto(-150,-50)
t.pendown()
t.setheading(90)
t.fillcolor("cornflowerblue")
t.begin_fill()
t.circle(10,180)
t.end_fill()
t.setheading(90)
t.begin_fill()
t.circle(10,180)
t.end_fill()
t.setheading(90)
t.begin_fill()
t.circle(10,180)
t.end_fill()
t.setheading(90)
t.begin_fill()
t.circle(10,180)
t.end_fill()
t.setheading(90)
t.begin_fill()
t.circle(10,180)
t.end_fill()

t.penup()
t.goto(-200,-50)
t.pendown()
t.pencolor("saddlebrown")
t.pensize(8)
t.goto(-200,-125)

t.setheading(50)
t.penup()
t.goto(-40,-175)
t.pendown()
t.pencolor("orchid")
t.fillcolor("plum")
t.begin_fill()
t.pensize(2)
t.forward(50)
t.right(90)
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(100)
t.end_fill()

t.setheading(0)
t.penup()
t.goto(-155,-250)
t.pendown()
t.pencolor("red")
t.fillcolor("red")
t.begin_fill()
t.circle(30)
t.end_fill()

t.penup()
t.goto(200,-220)
t.pendown()
t.pencolor("sienna")
t.pensize(4)
t.setheading(225)
t.forward(60)
t.setheading(270)
t.forward(45)
t.setheading(90)
t.forward(45)
t.setheading(180)
t.forward(60)
t.setheading(270)
t.forward(45)

t.pencolor("hotpink")
t.penup()
t.goto(0, 120)
t.pendown()
t.write("Spring into summer!", font=("Georgia", 30, "bold"), align="center")

turtle.done()